
# using this format : [players'IGN , previous player's timezone, players'IGN , previous player's timezone, ...]

# Timezone is defined on GMT (if it's 3, GMT+3, If it's -5, GMT-5, if it's 0, GMT)

# Writing this on 29/06/2023 : new season and so I saved the old one as "old_data", new one is "data"

data = [
    "ImBrayyy", -5,
    "BoboTM", 1,
    "MatijaZmaj", 1,
    "Brantonious", -5,
    "PotaraGoku", 1,
    "MikeMakesSkins", 1,
    "DimenSpace", 1,
    "bambuko19", 1,
    "Masterak326", 5,
    "TheDi4mondCat", 1,
    "QwertyQ1234", 1,
    "Plazmatron", 1,
    "meesecakes", 1,
    "SpaceGoose71", 5,
    "Mato879", 1,
    "Sehman", 3,
    "Cube713", 1,
    "Lava778", -8
]

old_data = [
    "BoboTM", 1,
    "Aztrani", 2,
    "DimenSpace", 2,
    "lemonswithlime", -4,
    "JangoTheSoviet", 5,
    "PvpNinjaPro", 2,
    "Skyl3r04", 8,
    "yellowish_cow", 3,
    "bambuko18", 1,
    "HeadShotHusky", 2,
    "threwt_shoot", 1,
    "lyxacii", 10,
    "V0pT", -4,
    "NNASA", -4,
    "MatijaZmaj", 2,
    "YumikM", 2,
    "Thebrayman68", -4,
    "Mato879", 1,
    "Potatotito", 2,
    "DiamondCat8888", 1,
    "QwertyQ1234", 1,
    "BostedLlama", 2,
    "AerobicMaple80", -5,
    "Paper1", -4,
    "mrsgabby", -4,
    "Plazmatron", 4,
    "mxtt12", 5,
    "Knockoff_Naomi", -4,
    "0meni", 5,
    "MrPanda42010", 5.5,
    "DestroyerXX99", 0,
    "ZSXF", 4,
    "Kaialva", -4,
    "Kapiteusz", 1,
    "rxmemberrl", 2,
    "WooFuzy", 2,
    "xRamana", -4,
    "VoidedWasTaken", 1,
    "Iuk_", 5,
    "TheRamenKing69", 1,
    "ImAlex404", 2,
    "Not_Marian", 2,
    "LunarXN", -4,
    "DasKleineKuken", -4,
    "thekingofgames12", -4,
    "_MrNarwhal", -4,
    "tremblero", -4,
    "ParadoxFlame", -7,
    "GudBagel", 1,
    "BloodForGambit", 2,
    "youmerguez", 2,
    "Masterak326", 5.5,
    "SpaceGoose71", 4,
    "Not_Marian", 2,
    "Brantonious", -4,
    "PossessedJelly", 4,
    "TheRoyalDiamond", -4,
    "Porkypin", 0,
    "jose521", -4,
    "GreyCreeper13", -4,
    "Senxei", -6,
    "Cube713", 0,
    "FlanDanTheMan", -5,
    "iTris", 0,
    "AgentNoodle", -7,
    "bluefreya", -7,
    "raysfxx", -7,
    "Mcskye22", 12,
    "Praisethesun", -6,
    "beanz00_", 12,
    "Thecopydino7", -4,
    "Tersoar", 0,
    "Cashdean", -4,
    "KeptEagle204390", -5,
    "Some1Random", -4,
    "Parallax25", -4,
    "meesecakes", 1,
    "SUBMSV_Foxmaid24", 8,
    "Stetsed", 2,
    "amazingDragonboy", 1
]