
# using this format : [players'IGN , previous player's timezone, players'IGN , previous player's timezone, ...]

# Timezone is defined on GMT (if it's 3, GMT+3, If it's -5, GMT-5, if it's 0, GMT)
data = [
    "BoboTM", 1,
    "Aztrani", 2,
    "DimenSpace", 2,
    "lemonswithlime", -4,
    "JangoTheSoviet", 5,
    "PvpNinjaPro", 2,
    "Skyl3r04", 8,
    "yellowish_cow", 3,
    "bambuko18", 1,
    "HeadShotHusky", 2,
    "threwt_shoot", 1,
    "lyxacii", 10,
    "V0pT", -4,
    "NNASA", -4,
    "MatijaZmaj", 2,
    "YumikM", 2,
    "Thebrayman68", -4,
    "Mato879", 1,
    "Potatotito", 2,
    "DiamondCat8888", 1,
    "QwertyQ1234", 1,
    "BostedLlama", 2,
    "AerobicMaple80", -5,
    "Paper1", -4,
    "mrsgabby", -4,
    "Plazmatron", 4,
    "mxtt12", 5,
    "Knockoff_Naomi", -4,
    "0meni", 5,
    "MrPanda42010", 5.5,
    "DestroyerXX99", 0,
    "ZSXF", 4,
    "Kaialva", -4,
    "Kapiteusz", 1,
    "rxmemberrl", 2
]